### PR TITLE
Update LibraryTest.java

### PR DESCRIPTION
**Pull request by nguyenducviet1999**
add Testpow()

### CODE REVIEW

**Comment by nayuki** [comment]
Please improve your style, or else I cannot accept your changes.

Name the function correctly, indent properly using exclusively tabs, and add a space after each comma.

Look at how I wrote my code and make yours blend in!

**Comment by nayuki** [comment]
Please improve your style, or else I cannot accept your changes.

Name the function correctly, indent properly using exclusively tabs, and add a space after each comma.

Look at my existing code as examples, and make yours blend in!

**Comment by nguyenducviet1999** [comment]
thank your idear.i will try harder

**Comment by nguyenducviet1999** [comment]
Can you accept my changes,please?

**Comment by nayuki** [comment]
You said you will try harder, but you didn't commit any new changes.

**Comment by nayuki** [comment]
I see no improvement in your code, despite my repeated attempts to impart you with advice. Firmly rejected.

**Pull request closed without merging**
