### PR TITLE
Update p004.py

### PR DESCRIPTION
**Pull request by rindazzz**
This works times faster without going through 2 full nested cycles.

### CODE REVIEW

**Comment by nayuki** [comment]
My Python solution #4 runs in 300 ms on my computer. In terms of absolute run time, there is no need to optimize it.

Even though the two loops can be considered "inefficient" in a relative sense, I do not like your code logic. It is not plain to see why your code is correct, nor have you commented or explained why the algorithm works. Either way, you noticeably increased the line count while providing minimal benefits, which I feel is a bad deal.

In my Project Euler solutions I choose to err on the side of clarity and verification-by-inspection instead of pulling all the optimization tricks.

Patch rejected.

**Comment by rindazzz** [comment]
That's strange, coming from somebody who managed to tackle all/almost all Euler project problems.
If you would look at PDF that shows up after the correct answer is posted, you would see that I implemented some of those ideas (unknowingly). First - start with highest numbers, then countdown.
Second - once you found your first palindrome:
580085=995*583
906609=993*913
906609
you don't have to count "j" any lower.
I'am doing it on my raspberry and computation time differs about 5 times.
And your condescending tone doesn't do any good either.
PS: Sorry for not providing any comments, I'am new to this.

**Comment by rindazzz** [comment]
Your cycle goes 810000 times, while my does 4872

**Comment by nayuki** [comment]
Thank you for the follow-up. I understand what's going on now, with regards to stopping the loop earlier once a result is found. I did measure the run time of your code and it was 10× faster at ~30 ms as claimed. I'm not saying that your code is technically wrong (in fact I assumed that it's correct before running it), but you initially didn't justify why the code warrants the extra complexity. In my mind, two nested loops is easy to check for correctness. The logic you presented, of reverse-counting loops with variable early stopping, was not clear at the outset. I would much prefer to have a slower solution that I can understand than a faster one that is longer and uses more advanced constructs. I value simplicity as a virtue.

I use the simplest code to solve a problem adequately (I feel that 300 ms is more than adequate) and move on. This should not have turned into a debate. For reference if you look at the screenshot below, optimizing problem #3 is not on my mind when I have far worse solutions to take care of, such as #70 and #92. I've got work to do - best regards.

Project Euler Python solution run times as of commit bf37dfd9d1793fb4ed0902f06cd9b7b3237c42e8

**Pull request closed without merging**
